QE-7182 | fix typos for endpoints and set duration to 60s
GannettDigital/quality-engineering-performance-testing pull request #4
Opened 2020-10-19 18:46 UTC by amalhotragannett

2020-10-19 19:17 UTC, mmillgate requested changes
some clarification questions

2020-10-19 19:17 UTC, mmillgate commented on elections-2020/src/artillery-utils.js
>              `format=uwResponse&site-code=${market.siteCode}&dataID=2018-11-06-senate-AZ-4021`
why is the date on this one 2018-11-06?

2020-10-19 19:17 UTC, mmillgate commented on elections-2020/src/artillery-utils.js
>              `format=uwResponse&site-code=${market.siteCode}&electionDate=2020-11-03`
I'm concerned with the hardcoded date values being set for a future date during the up coming AP test windows, does this need to be configurable to work within the AP testing windows, or do they accept future dates and provide valid data?

2020-10-19 19:17 UTC, mmillgate commented on elections-2020/src/artillery-utils.js
>              `format=uwResponse&site-code=${market.siteCode}&electionDate=2020-11-03&state=california`
if the state-market.name value is changing dynamically, should the `&state=california` value of the URL also be changing dynamically?  Does it make sense to be seeing/getting California data if the state-market.name was set to Utah as an example?

2020-10-19 19:17 UTC, mmillgate commented on elections-2020/src/artillery-utils.js
>              `format=uwResponse&site-code=${market.siteCode}&dataID=2018-11-06-senate-AZ-4021`
should the `senate-AZ-4021` dataID QSP value be dynamically set as well based on single-race-market.name?

2020-10-19 19:17 UTC, mmillgate commented on elections-2020/src/artillery-utils.js
>              `format=uwResponse&level=upper&site-code=${market.siteCode}&electionDate=2020-11-03&state=california`
this url and the url for state-house below are basically the same endpoint the only difference is the level QSP value.   Is the performance based on the endpoint of the QSP?

2020-10-19 19:17 UTC, mmillgate commented on elections-2020/src/artillery-utils.js
>              `format=uwResponse&level=lower&site-code=${market.siteCode}&electionDate=2020-11-03&state=california`
the format=uwResponse is acceptable for Tangent sites and they are not required for the home-page-summary, summary-bop, key-races flows?

2020-10-19 19:21 UTC, amalhotragannett commented on elections-2020/src/artillery-utils.js
>              `format=uwResponse&site-code=${market.siteCode}&dataID=2018-11-06-senate-AZ-4021`
These were the URLS provided by Brendan that we had to run performance tests on. Yes, that is an option to set those dynamically. Let me find a way to optimize this if I can.

2020-10-19 19:28 UTC, amalhotragannett commented on elections-2020/src/artillery-utils.js
>              `format=uwResponse&site-code=${market.siteCode}&electionDate=2020-11-03`
Good point. URLs provided by Brendan. Will check for how election dates are working.

2020-10-19 19:29 UTC, amalhotragannett commented on elections-2020/src/artillery-utils.js
>              `format=uwResponse&level=upper&site-code=${market.siteCode}&electionDate=2020-11-03&state=california`
The difference is the site code. I will inject state values for these.

2020-10-19 19:29 UTC, amalhotragannett commented on elections-2020/src/artillery-utils.js
>              `format=uwResponse&level=lower&site-code=${market.siteCode}&electionDate=2020-11-03&state=california`
A very good catch. I will enable both `uwResponse` and `tangent`

2020-10-19 20:03 UTC, amalhotragannett commented on elections-2020/src/artillery-utils.js
>              `format=uwResponse&site-code=${market.siteCode}&dataID=2018-11-06-senate-AZ-4021`
I tried setting this dynamic data but couldn't find a way in this short notice.

2020-10-20 15:48 UTC, mmillgate approved these changes

2020-10-20 15:48 UTC, merged